[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "replayer_backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "python-multipart"
]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["app"]